=== Danmarjim/mwm-2014-2015/Mod2/XML/Peliculas/Peliculas.xsd
<?xml version="1.0" encoding="windows-1252" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.example.org"
            targetNamespace="http://www.example.org" elementFormDefault="qualified">
  <xsd:simpleType name="tipoT">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="drama"/>
      <xsd:enumeration value="comedia"/>
      <xsd:enumeration value="misterio"/>
      <xsd:enumeration value="terror"/>
      <xsd:enumeration value="aventuras"/>
      <xsd:enumeration value="ciencia-ficcion"/>
      <xsd:enumeration value="documental"/>
      <xsd:enumeration value="romantica"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="peliculaT">
    <xsd:sequence>
      <xsd:element name="titulo" type="xsd:string"/>
      <xsd:element name="guionista" type="xsd:string" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="productor" type="xsd:string" maxOccurs="unbounded"/>
      <xsd:element name="director" type="xsd:string"/>
      <xsd:element name="actor" type="xsd:string" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="comentarios" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="tipo" type="tipoT"/>
    <xsd:attribute name="año" type="xsd:integer"/>
  </xsd:complexType>
  <xsd:element name="peliculas">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="pelicula" type="peliculaT" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Danmarjim/mwm-2014-2015/Mod2/XML/Peliculas/classes/PeliculasConEsquema.xml
<?xml version="1.0" encoding="windows-1252" ?>
<peliculas xmlns="http://www.example.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.example.org peliculas.xsd">
  <pelicula tipo="comedia" año="1987">
    <titulo>Raising Arizona</titulo>
    <guionista>Ethan Coen</guionista>
    <guionista>Joel Coen</guionista>
    <productor>Ethan Coen</productor>
    <director>Joel Coen</director>
    <actor>Nicolas Cage</actor>
    <actor>Holly Hunter</actor>
    <actor>John Goodman</actor>
    <comentarios>Una historia de amor con final inusitado</comentarios>
  </pelicula>
  <pelicula tipo="comedia" año="1988">
    <titulo>Midnight Run</titulo>
    <guionista>George Gallo</guionista>
    <productor>Martin Brest</productor>
    <director>Martin Brest</director>
    <actor>Robert De Niro</actor>
    <actor>Charles Grodin</actor>
    <comentarios>La quinta esencia de las comedias de carretera</comentarios>
  </pelicula>
  <pelicula tipo="misterio" año="1995">
    <titulo>The Usual Suspects</titulo>
    <guionista>Christopher McQuarrie</guionista>
    <productor>Bryan Singer</productor>
    <productor>Michael McDonnell</productor>
    <director>Bryan Singer</director>
    <actor>Stephen Baldwin</actor>
    <actor>Gabriel Byrne</actor>
    <actor>Benicio Del Toro</actor>
    <actor>Chazz Palminten</actor>
    <actor>Kevin Pollak</actor>
    <actor>Kevin Spacey</actor>
    <comentarios>Un crimen con cambios en el argumento muy intrincados</comentarios>
  </pelicula>
  <pelicula tipo="ciencia-ficcion" año="1989">
    <titulo>The Abyss</titulo>
    <guionista>James Cameron</guionista>
    <productor>Gale Anne Hurd</productor>
    <director>James Cameron</director>
    <actor>Ed Harris</actor>
    <actor>Mary Elizabeth Mastrantonio</actor>
    <comentarios>Una odisea submarina muy comprometida</comentarios>
  </pelicula>
</peliculas>
