=== Danmarjim/mwm-2014-2015/Mod2/XML/Incendios/Incendios.xsd
<?xml version="1.0" encoding="windows-1252" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.example.org"
            targetNamespace="http://www.example.org" elementFormDefault="qualified">
  <xsd:complexType name="incendioT">
    <xsd:sequence>
      <xsd:element name="localidad" type="xsd:string"/>
      <xsd:element name="coordenadas" type="xsd:string"/>
      <xsd:element name="hectareasB" type="xsd:integer" minOccurs="0"/>
      <xsd:element name="hectareasM" type="xsd:integer" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="magnitud" type="xsd:integer"/>
    <xsd:attribute name="controlado" type="xsd:boolean"/>
  </xsd:complexType>
  <xsd:element name="incendios">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="incendio" type="incendioT" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Danmarjim/mwm-2014-2015/Mod2/XML/Incendios/classes/IncendiosConXSD.xml
<?xml version="1.0" encoding="windows-1252" ?>
<incendios xmlns="http://www.example.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.example.org incendios.xsd">
    <incendio controlado="false" magnitud="15">
        <localidad>Las Rozas</localidad>
        <coordenadas>(250,350)</coordenadas>
        <hectareasB>120</hectareasB>
        <hectareasM>45</hectareasM>
    </incendio>
    <incendio controlado="false" magnitud="7">
        <localidad>Pedrera</localidad>
        <coordenadas>(300,140)</coordenadas>
        <hectareasB>20</hectareasB>
        <hectareasM></hectareasM>
    </incendio>
    <incendio controlado="true" magnitud="5">
        <localidad>Linares</localidad>
        <coordenadas>(485,200)</coordenadas>
        <hectareasB></hectareasB>
        <hectareasM>17</hectareasM>
    </incendio>
    <incendio controlado="false" magnitud="10">
        <localidad>San Vicente de la Barquera</localidad>
        <coordenadas>(550,200)</coordenadas>
        <hectareasB></hectareasB>
        <hectareasM>57</hectareasM>
    </incendio>
    <incendio controlado="true" magnitud="2">
        <localidad>San Feliu de Llobregat</localidad>
        <coordenadas>(400,320)</coordenadas>
        <hectareasB>3</hectareasB>
        <hectareasM>5</hectareasM>
    </incendio>
</incendios>
