=== Danmarjim/mwm-2014-2015/Mod2/XML/Evaluacion/classes/Incendios.xsd
<?xml version="1.0" encoding="windows-1252" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.example.org"
            targetNamespace="http://www.example.org" elementFormDefault="qualified">
  <xsd:simpleType name="tipoT">
    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>
  <xsd:complexType name="incendioT">
    <xsd:sequence>
      <xsd:element name="localidad" type="xsd:string"/>
      <xsd:element name="coordenadas" type="xsd:string"/>
      <xsd:element name="magnitud" type="xsd:integer"/>
      <xsd:element name="hectareasbosque" minOccurs="0" type="xsd:integer"/>
      <xsd:element name="hectareasmatorral" type="xsd:integer" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="incendios">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="incendio" type="incendioT" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Danmarjim/mwm-2014-2015/Mod2/XML/Evaluacion/classes/IncendiosConXSD.xml
<?xml version="1.0" encoding="windows-1252" ?>
<incendios xmlns="http://www.example.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.example.org incendios.xsd">
    <incendio>
        <localidad>Las Rozas</localidad>
        <coordenadas>(250,350)</coordenadas>
        <magnitud>15</magnitud>
        <hectareasbosque>120</hectareasbosque>
        <hectareasmatorral>45</hectareasmatorral>
    </incendio>
    <incendio>
        <localidad>San Feliu de Llobregat</localidad>
        <coordenadas>(550,200)</coordenadas>
        <magnitud>10</magnitud>
        <hectareasbosque>10</hectareasbosque>
        <hectareasmatorral>57</hectareasmatorral>
    </incendio>
    <incendio>
        <localidad>Pedrera</localidad>
        <coordenadas>(300,140)</coordenadas>
        <magnitud>7</magnitud>
        <hectareasbosque>20</hectareasbosque>
        <hectareasmatorral>10</hectareasmatorral>
    </incendio>
    <incendio>
        <localidad>Linares</localidad>
        <coordenadas>(485,420)</coordenadas>
        <magnitud>5</magnitud>
        <hectareasbosque>10</hectareasbosque>
        <hectareasmatorral>17</hectareasmatorral>
    </incendio>
    <incendio>
        <localidad>San Vicente de Barquera</localidad>
        <coordenadas>(400,320)</coordenadas>
        <magnitud>2</magnitud>
        <hectareasbosque>3</hectareasbosque>
        <hectareasmatorral>5</hectareasmatorral>
    </incendio>
</incendios>
